### ISSUE TITLE
Deploying mongodb fails with "Error parsing command line: unrecognised option '--smallfiles'

### ISSUE THREAD

**Issue by ekuric** [cloud-bulldozer/marshall-plan#11]
executing 

```
git clone https://github.com/cloud-bulldozer/marshall-plan
cd marshall-plan
oc project my-ripsaw
kubectl apply -f deploy
kubectl apply -f resources/crds/infra_v1alpha1_builder_crd.yaml
kubectl apply -f resources/namespace.yaml 
kubectl apply -f resources/operator.yaml
kubectl apply -f infra_v1alpha1_mongo_cr.yaml
```
leads to mongpod to fail to start and report 

```
# oc logs mongo0-0 
Error parsing command line: unrecognised option '--smallfiles'
try 'mongod --help' for more information
```

```
 # cat infra_v1alpha1_mongo_cr.yaml 
apiVersion: builder.cloudbulldozer.io/v1alpha1
kind: Infra
metadata:
  name: mongo-infra
  namespace: builder-infra
spec:
  infrastructure:
    name: mongo
    args:
      tag: 4
      clusters: 2 # number of mongo clusters
      cluster_size: 3 # number of pods per mongo cluster
      storageclass: ocs-storagecluster-ceph-rbd  # uses the sc with the annotation storageclass.kubernetes.io/is-default-class: "true" if the option is not specified
      storagesize: 10Gi # default value if option not specified
      port: 27017 # default value if option not specified
      extra_options: # list of extra options that need to be passed as is to starting mongo daemon
        - "--smallfiles"
        - "--noprealloc"
```
